const CreateFichaNPCUseCase = require("./CreateFichaNPCUseCase");

class CreateFichaNPCController {
  async handle(request, response) {
    const {
      nome,
      classe,
      origem,
      nacionalidade,
      idade,
      nex,
      trilha,
      patente,
      agi,
      int,
      vig,
      pre,
      forca,
      pvMax,
      psMax,
      peMax,
      acrobacia,
      adestramento,
      arte,
      atletismo,
      atualidade,
      ciencia,
      crime,
      diplomacia,
      enganacao,
      fortitude,
      furtividade,
      iniciativa,
      intimidacao,
      intuicao,
      investigacao,
      luta,
      medicina,
      ocultismo,
      percepcao,
      pilotagem,
      pontaria,
      profissao,
      reflexo,
      religiao,
      sobrevivencia,
      tatica,
      tecnologia,
      vontade,
      passiva,
      esquiva,
      bloqueio,
      mental,
      morte,
      conhecimento,
      sangue,
      energia,
      fisica,
      balistica,
      corte,
      impacto,
      perfuracao,
      eletricidade,
      fogo,
      frio,
      quimica,
      inventario,
      habilidades,
      ataques,
      detalhes,
      sessaoId
    } = request.body;

    const createFichaNPCUseCase = new CreateFichaNPCUseCase();

    const fichaNPC = await createFichaNPCUseCase.execute({

      nome,
      classe,
      origem,
      nacionalidade,
      idade,
      nex,
      trilha,
      patente,

      agi,
      int,
      vig,
      pre,
      forca,

      pvMax,
      psMax,
      peMax,

      acrobacia,
      adestramento,
      arte,
      atletismo,
      atualidade,
      ciencia,
      crime,
      diplomacia,
      enganacao,
      fortitude,
      furtividade,
      iniciativa,
      intimidacao,
      intuicao,
      investigacao,
      luta,
      medicina,
      ocultismo,
      percepcao,
      pilotagem,
      pontaria,
      profissao,
      reflexo,
      religiao,
      sobrevivencia,
      tatica,
      tecnologia,
      vontade,
      passiva,
      esquiva,
      bloqueio,
      mental,
      morte,
      conhecimento,
      sangue,
      energia,
      fisica,
      balistica,
      corte,
      impacto,
      perfuracao,
      eletricidade,
      fogo,
      frio,
      quimica,
      inventario,
      ataques,
      habilidades,
      detalhes,

      sessaoId

    });
    response.status(201).json(fichaNPC);
  }
}

module.exports = CreateFichaNPCController;
