const EditFichaNPCUseCase = require("./EditFichaNPCUseCase");

class EditFichaNPCController {
  async handle(request, response) {
    const {
      nome,
      delocamento,
      peso,
      classe,
      origem,
      nacionalidade,
      idade,
      nex,
      trilha,
      patente,
      agi,
      int,
      vig,
      pre,
      forca,
      pv,
      ps,
      pe,
      pvMax,
      psMax,
      peMax,
      acrobacia,
      adestramento,
      arte,
      atletismo,
      atualidade,
      ciencia,
      crime,
      diplomacia,
      enganacao,
      fortitude,
      furtividade,
      iniciativa,
      intimidacao,
      intuicao,
      investigacao,
      luta,
      medicina,
      ocultismo,
      percepcao,
      pilotagem,
      pontaria,
      profissao,
      reflexo,
      religiao,
      sobrevivencia,
      tatica,
      tecnologia,
      vontade,
      passiva,
      esquiva,
      bloqueio,
      mental,
      morte,
      conhecimento,
      sangue,
      energia,
      fisica,
      balistica,
      corte,
      impacto,
      perfuracao,
      eletricidade,
      fogo,
      frio,
      quimica,
      inventario,
      habilidades,
      detalhes
    } = request.body;

    const { id } = request.params

    const editFichaNPCUseCase = new EditFichaNPCUseCase();

    const fichaNPC = await editFichaNPCUseCase.execute({
      id,
      nome,
      delocamento,
      peso,
      classe,
      origem,
      nacionalidade,
      idade,
      nex,
      trilha,
      patente,

      agi,
      int,
      vig,
      pre,
      forca,

      pv,
      ps,
      pe,
      pvMax,
      psMax,
      peMax,

      acrobacia,
      adestramento,
      arte,
      atletismo,
      atualidade,
      ciencia,
      crime,
      diplomacia,
      enganacao,
      fortitude,
      furtividade,
      iniciativa,
      intimidacao,
      intuicao,
      investigacao,
      luta,
      medicina,
      ocultismo,
      percepcao,
      pilotagem,
      pontaria,
      profissao,
      reflexo,
      religiao,
      sobrevivencia,
      tatica,
      tecnologia,
      vontade,
      passiva,
      esquiva,
      bloqueio,
      mental,
      morte,
      conhecimento,
      sangue,
      energia,
      fisica,
      balistica,
      corte,
      impacto,
      perfuracao,
      eletricidade,
      fogo,
      frio,
      quimica,
      inventario,
      habilidades,
      detalhes,

    });
    response.status(201).json(fichaNPC);
  }
}

module.exports = EditFichaNPCController;
